/**
 * Created by scvalencia606 on 1/21/17.
 */
public enum ASTNodeType {

    IDENTIFIER, STRING, INTEGER, SEQUENCE, IF, PRT_CHAR, PRT_STRING, PRT_IDENTIFIER,

    WHILE, ASSIGN, NEGATE, NOT, MULTIPLICATION, DIVISION, MODULO, ADDITION, SUBTRACTION,

    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, EQUAL, NOT_EQUAL, AND, OR,

    NONE
}
